"""ASF initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-04 00:00:00.000000

Creates the complete ASF domain schema. The migration is hand-written
(not autogenerated) so that the DDL is deterministic across re-deploys
and so that the PostgreSQL-specific bits (native ENUM types, JSONB
columns, ON DELETE CASCADE foreign keys) are explicit. It is also
deliberately idempotent in spirit: running ``alembic upgrade head``
twice in a row is a no-op because the ``alembic_version`` table
records the current revision; running the same SQL twice without the
version table would error.

Tables created (all in the public schema by default):

* ``missions``      — top-level orchestration record
* ``agents``        — PraisonAI agent per role
* ``tasks``         — unit of work assigned to an agent
* ``executions``    — single execution attempt of a task
* ``approvals``     — human review decision for a mission gate
* ``chat_messages`` — PM-Chat lines attached to a mission

The migration also creates the following PostgreSQL ENUM types:

* ``mission_status``
* ``agent_role``
* ``agent_status``
* ``task_status``
* ``execution_status``
* ``approval_gate_type``
* ``approval_decision``
* ``chat_sender_type``

ENUMs are wrapped in ``CREATE TYPE IF NOT EXISTS`` *blocks*; the
revision itself is guarded by the ``alembic_version`` table so the
DDL only runs once. A downgrade drops every table and enum.

Notable design points:

* Foreign keys are declared ``ON DELETE CASCADE`` so that removing a
  mission purges its agents, tasks, executions, approvals, and chat
  messages. The ``chat_messages.sender_id`` FK uses ``ON DELETE SET
  NULL`` instead, because a chat history should survive the deletion
  of the agent that wrote it.
* Every table has ``created_at`` and ``updated_at`` ``TIMESTAMP WITH
  TIME ZONE`` columns (the application bumps ``updated_at``
  explicitly; we do not rely on ``ON UPDATE`` because it is not
  portable to SQLite, which the test suite uses).
* The status / role / sender columns are stored as PostgreSQL native
  ENUM types, which constrain the allowed values on PostgreSQL (the
  production backend). Only ``missions.status`` additionally carries
  an explicit portable ``CHECK`` constraint (``ck_missions_status``);
  the other enum columns rely on the PG ENUM type alone. On SQLite
  (the test backend) native enums render as bare ``VARCHAR`` with no
  CHECK, so value validation there is enforced by the SQLAlchemy ORM
  enum types at insert time rather than at the database level.
* B-tree indexes are added on ``missions(status)`` and
  ``missions(created_at)`` to keep list queries cheap. Additional
  indexes are added on the foreign-key columns and on
  ``executions(status)`` / ``chat_messages(sender_type)`` /
  ``chat_messages(created_at)`` because those are common filter
  columns in API endpoints.
* Unstructured metadata columns are declared as ``JSONB`` on
  PostgreSQL and ``JSON`` on SQLite (using
  ``sa.JSON().with_variant(JSONB(), "sqlite")``).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _jsonb_column() -> sa.types.TypeEngine:
    """Return a ``JSONB`` column on PostgreSQL, ``JSON`` elsewhere.

    Using a helper keeps the migration readable and makes the variant
    policy explicit in one place.
    """
    return postgresql.JSONB().with_variant(sa.JSON(), "sqlite")


def _uuid_column() -> sa.types.TypeEngine:
    """Return a UUID column on PostgreSQL, CHAR(36) on SQLite.

    SQLAlchemy's ``UUID`` type on SQLite falls back to ``CHAR(36)`` so
    the same model can be used in unit tests without a running
    PostgreSQL instance.
    """
    return postgresql.UUID(as_uuid=True).with_variant(sa.String(36), "sqlite")


# ---------------------------------------------------------------------------
# ENUM value tuples — kept in sync with soy.models.enums
# ---------------------------------------------------------------------------
_MISSION_STATUS = (
    "created", "planning", "approved", "rejected",
    "execution", "reviewed", "merged", "escalated",
)
_AGENT_ROLE = ("coder", "qa", "reviewer", "orchestrator")
_AGENT_STATUS = ("idle", "working", "paused", "failed", "completed")
_TASK_STATUS = ("pending", "running", "completed", "failed", "escalated")
_EXECUTION_STATUS = (
    "queued", "running", "completed", "failed", "cancelled", "timeout",
)
_APPROVAL_GATE_TYPE = ("planning", "merge")
_APPROVAL_DECISION = ("approve", "reject")
_CHAT_SENDER_TYPE = ("user", "agent", "system")


def upgrade() -> None:
    """Create the ASF schema."""

    # -- 1. ENUM types -------------------------------------------------
    mission_status = postgresql.ENUM(*_MISSION_STATUS, name="mission_status")
    agent_role = postgresql.ENUM(*_AGENT_ROLE, name="agent_role")
    agent_status = postgresql.ENUM(*_AGENT_STATUS, name="agent_status")
    task_status = postgresql.ENUM(*_TASK_STATUS, name="task_status")
    execution_status = postgresql.ENUM(*_EXECUTION_STATUS, name="execution_status")
    approval_gate_type = postgresql.ENUM(*_APPROVAL_GATE_TYPE, name="approval_gate_type")
    approval_decision = postgresql.ENUM(*_APPROVAL_DECISION, name="approval_decision")
    chat_sender_type = postgresql.ENUM(*_CHAT_SENDER_TYPE, name="chat_sender_type")

    mission_status.create(op.get_bind(), checkfirst=True)
    agent_role.create(op.get_bind(), checkfirst=True)
    agent_status.create(op.get_bind(), checkfirst=True)
    task_status.create(op.get_bind(), checkfirst=True)
    execution_status.create(op.get_bind(), checkfirst=True)
    approval_gate_type.create(op.get_bind(), checkfirst=True)
    approval_decision.create(op.get_bind(), checkfirst=True)
    chat_sender_type.create(op.get_bind(), checkfirst=True)

    # -- 2. missions ---------------------------------------------------
    op.create_table(
        "missions",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column("issue_id", sa.String(length=64), nullable=True),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("branch", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                *_MISSION_STATUS,
                name="mission_status",
                create_type=False,  # type already created above
            ),
            nullable=False,
            server_default="created",
        ),
        sa.Column("spec_path", sa.String(length=512), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("spec_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("merge_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("metadata", _jsonb_column(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.CheckConstraint(
            "status IN ('created','planning','approved','rejected',"
            "'execution','reviewed','merged','escalated')",
            name="ck_missions_status",
        ),
    )
    op.create_index("ix_missions_status", "missions", ["status"])
    op.create_index("ix_missions_created_at", "missions", ["created_at"])

    # -- 3. agents -----------------------------------------------------
    op.create_table(
        "agents",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column(
            "mission_id",
            _uuid_column(),
            sa.ForeignKey("missions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                *_AGENT_ROLE, name="agent_role", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("llm_config", _jsonb_column(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                *_AGENT_STATUS, name="agent_status", create_type=False,
            ),
            nullable=False,
            server_default="idle",
        ),
        sa.Column("tool_config", _jsonb_column(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        # NOTE: the ``sandbox`` column is intentionally NOT created
        # here — revision 0003 owns its entire lifecycle (add on
        # upgrade, drop on downgrade), mirroring how 0002 owns
        # ``branch_prefix``. This keeps 0003 reversible.
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("ix_agents_mission_id", "agents", ["mission_id"])
    op.create_index("ix_agents_role", "agents", ["role"])

    # -- 4. tasks ------------------------------------------------------
    op.create_table(
        "tasks",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column(
            "mission_id",
            _uuid_column(),
            sa.ForeignKey("missions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            _uuid_column(),
            sa.ForeignKey("agents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                *_TASK_STATUS, name="task_status", create_type=False,
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("depends_on", _jsonb_column(), nullable=True),
        sa.Column(
            "attempt_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column("config", _jsonb_column(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("ix_tasks_mission_id", "tasks", ["mission_id"])
    op.create_index("ix_tasks_agent_id", "tasks", ["agent_id"])
    op.create_index("ix_tasks_status", "tasks", ["status"])

    # -- 5. executions -------------------------------------------------
    op.create_table(
        "executions",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column(
            "task_id",
            _uuid_column(),
            sa.ForeignKey("tasks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            _uuid_column(),
            sa.ForeignKey("agents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "mission_id",
            _uuid_column(),
            sa.ForeignKey("missions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                *_EXECUTION_STATUS, name="execution_status", create_type=False,
            ),
            nullable=False,
            server_default="queued",
        ),
        sa.Column(
            "attempt_number",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
        sa.Column("output", _jsonb_column(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("ix_executions_task_id", "executions", ["task_id"])
    op.create_index("ix_executions_agent_id", "executions", ["agent_id"])
    op.create_index("ix_executions_mission_id", "executions", ["mission_id"])
    op.create_index("ix_executions_status", "executions", ["status"])

    # -- 6. approvals --------------------------------------------------
    op.create_table(
        "approvals",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column(
            "mission_id",
            _uuid_column(),
            sa.ForeignKey("missions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "gate_type",
            postgresql.ENUM(
                *_APPROVAL_GATE_TYPE,
                name="approval_gate_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision",
            postgresql.ENUM(
                *_APPROVAL_DECISION, name="approval_decision", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index("ix_approvals_mission_id", "approvals", ["mission_id"])
    op.create_index("ix_approvals_decision", "approvals", ["decision"])

    # -- 7. chat_messages ---------------------------------------------
    op.create_table(
        "chat_messages",
        sa.Column("id", _uuid_column(), primary_key=True, nullable=False),
        sa.Column(
            "mission_id",
            _uuid_column(),
            sa.ForeignKey("missions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "sender_type",
            postgresql.ENUM(
                *_CHAT_SENDER_TYPE, name="chat_sender_type", create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "sender_id",
            _uuid_column(),
            sa.ForeignKey("agents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("sender_name", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.create_index(
        "ix_chat_messages_mission_id", "chat_messages", ["mission_id"]
    )
    op.create_index(
        "ix_chat_messages_sender_type", "chat_messages", ["sender_type"]
    )
    op.create_index(
        "ix_chat_messages_created_at", "chat_messages", ["created_at"]
    )


def downgrade() -> None:
    """Drop every ASF table and enum in reverse order."""
    op.drop_index("ix_chat_messages_created_at", table_name="chat_messages")
    op.drop_index("ix_chat_messages_sender_type", table_name="chat_messages")
    op.drop_index("ix_chat_messages_mission_id", table_name="chat_messages")
    op.drop_table("chat_messages")

    op.drop_index("ix_approvals_decision", table_name="approvals")
    op.drop_index("ix_approvals_mission_id", table_name="approvals")
    op.drop_table("approvals")

    op.drop_index("ix_executions_status", table_name="executions")
    op.drop_index("ix_executions_mission_id", table_name="executions")
    op.drop_index("ix_executions_agent_id", table_name="executions")
    op.drop_index("ix_executions_task_id", table_name="executions")
    op.drop_table("executions")

    op.drop_index("ix_tasks_status", table_name="tasks")
    op.drop_index("ix_tasks_agent_id", table_name="tasks")
    op.drop_index("ix_tasks_mission_id", table_name="tasks")
    op.drop_table("tasks")

    op.drop_index("ix_agents_role", table_name="agents")
    op.drop_index("ix_agents_mission_id", table_name="agents")
    op.drop_table("agents")

    op.drop_index("ix_missions_created_at", table_name="missions")
    op.drop_index("ix_missions_status", table_name="missions")
    op.drop_table("missions")

    # Drop ENUM types last — they depend on the table columns existing
    # in the schema for type checks, but PostgreSQL allows drop after
    # the columns are gone. Use ``checkfirst`` to make the downgrade
    # safe to re-run.
    bind = op.get_bind()
    for enum_name in (
        "chat_sender_type",
        "approval_decision",
        "approval_gate_type",
        "execution_status",
        "task_status",
        "agent_status",
        "agent_role",
        "mission_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
